"""fix_order_status_pk

Revision ID: 04776e704079
Revises: a122cd2e3b6e
Create Date: 2026-06-07 14:29:39.308561

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04776e704079"
down_revision: Union[str, Sequence[str], None] = "a122cd2e3b6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure uuid-ossp extension exists for uuid_generate_v4()
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    # 1. Add id column as nullable
    op.add_column("order_statuses", sa.Column("id", sa.UUID(), nullable=True))

    # 2. Populate existing rows with unique UUIDs
    op.execute("UPDATE order_statuses SET id = uuid_generate_v4() WHERE id IS NULL")

    # 3. Set id to NOT NULL
    op.alter_column("order_statuses", "id", nullable=False)

    # 4. Drop the existing primary key (which was on order_id)
    # We need to find the constraint name. In many cases it's 'order_statuses_pkey'
    op.drop_constraint("order_statuses_pkey", "order_statuses", type_="primary")

    # 5. Create new primary key on 'id'
    op.create_primary_key("order_statuses_pkey", "order_statuses", ["id"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order_statuses", type_="unique")
    op.drop_column("order_statuses", "id")
    # ### end Alembic commands ###
