"""change_idempotency_key_to_text

Revision ID: 0a24d6873807
Revises: 85cb16f778f0
Create Date: 2026-06-07 12:50:49.608841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a24d6873807"
down_revision: Union[str, Sequence[str], None] = "85cb16f778f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "idempotency_keys",
        "idempotency_key",
        existing_type=sa.UUID(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "idempotency_keys",
        "idempotency_key",
        existing_type=sa.TEXT(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end 