"""idempotency key table add

Revision ID: 85cb16f778f0
Revises: 74b645dcaca5
Create Date: 2026-06-05 18:28:07.508353

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85cb16f778f0"
down_revision: Union[str, Sequence[str], None] = "74b645dcaca5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_keys",
        sa.Column("idempotency_key", sa.UUID(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("idempotency_key"),
    )
    op.create_unique_constraint(None, "orders", ["id"])
    op.create_unique_constraint(None, "outbox_events", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "outbox_events", type_="unique")
    op.drop_constraint(None, "orders", type_="unique")
    op.drop_table("idempotency_keys")
    # ### end Alembic commands ###
