"""add_idempotency_key_to_outbox

Revision ID: a122cd2e3b6e
Revises: fd4a4483508b
Create Date: 2026-06-07 14:02:43.066598

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a122cd2e3b6e"
down_revision: Union[str, Sequence[str], None] = "fd4a4483508b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbox_events", sa.Column("idempotency_key", sa.TEXT(), nullable=False)
    )
    op.create_unique_constraint(None, "outbox_events", ["idempotency_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "outbox_events", type_="unique")
    op.drop_column("outbox_events", "idempotency_key")
    # ### end Alembic commands ###
