"""add_quantity_to_orders

Revision ID: fd4a4483508b
Revises: 0a24d6873807
Create Date: 2026-06-07 13:49:58.164199

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd4a4483508b"
down_revision: Union[str, Sequence[str], None] = "0a24d6873807"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("quantity", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "quantity")
    # ### end Alembic commands ###
